version: '3.8'

services:

  web:
    build: .
    command: python3 manage.py runserver
    volumes: 
    - .:/app
    ports:
    - "8000:8000"
    environment:
      # These now read from the .env file
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASS}
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: postgres:17.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      # These also read from the .env file
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}

volumes:
  postgres_data: