# Generated by Django 5.2.4 on 2025-07-29 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_period_in_days', models.IntegerField(default=7)),
                ('issue_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('copies_available_after_loan', models.IntegerField()),
                ('readium_link', models.URLField()),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned')], default='issued')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.booksmodel')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.patronsmodel')),
            ],
        ),
    ]
