# Generated by Django 5.2 on 2025-04-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ISBN', models.BigIntegerField()),
                ('Publisher', models.CharField(max_length=255)),
                ('no_of_copies', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('checked_out', 'Checked Out'), ('missing', 'Missing'), ('damaged', 'Damaged')])),
                ('additional_tags', models.CharField(default='N/A')),
                ('authors', models.ManyToManyField(related_name='books', to='lending.author')),
            ],
        ),
    ]
